(function(global){
"use strict";
const STORAGE_KEY="warcraft.mockup.roster.v1";
const PARTY_SIZES=[3,5,10,20];
const DEFAULT_HEROES=[
{id:"mage",name:"Elowen",race:"Human",faction:"Alliance",classId:"mage",classLabel:"Mage",level:5,spec:"Fire",primary:"Intellect",availability:"available"},
{id:"rogue",name:"Valeera",race:"Undead",faction:"Horde",classId:"rogue",classLabel:"Rogue",level:4,spec:"Combat",primary:"Agility",availability:"available"},
{id:"warlock",name:"Mordren",race:"Undead",faction:"Horde",classId:"warlock",classLabel:"Warlock",level:3,spec:"Demonology",primary:"Intellect",availability:"on-quest"},
{id:"warrior",name:"Brom",race:"Dwarf",faction:"Alliance",classId:"warrior",classLabel:"Warrior",level:5,spec:"Arms",primary:"Strength",availability:"available"},
{id:"priest",name:"Sister Anwen",race:"Human",faction:"Alliance",classId:"priest",classLabel:"Priest",level:2,spec:"Holy",primary:"Intellect",availability:"available"},
{id:"druid",name:"Thorn",race:"Night Elf",faction:"Alliance",classId:"druid",classLabel:"Druid",level:4,spec:"Feral",primary:"Agility",availability:"available"},
{id:"hunter",name:"Rifleman Keg",race:"Dwarf",faction:"Alliance",classId:"hunter",classLabel:"Hunter",level:3,spec:"Marksmanship",primary:"Agility",availability:"available"},
{id:"paladin",name:"Arthoran",race:"Human",faction:"Alliance",classId:"paladin",classLabel:"Paladin",level:5,spec:"Retribution",primary:"Strength",availability:"on-quest"},
{id:"shaman",name:"Gorak",race:"Tauren",faction:"Horde",classId:"shaman",classLabel:"Shaman",level:1,spec:"Enhancement",primary:"Agility",availability:"available"}
];
function blankEquipment(){return {Head:null,Chest:null,Pants:null,Feet:null,Gloves:null,Weapon:null,Trinket:null};}
function defaultQuestBoard(){return {round:1,seed:"questboard-v1",offerIds:[]};}
function defaults(){return {faction:"alliance",heroes:DEFAULT_HEROES.map(h=>Object.assign({},h,{equipment:blankEquipment(),talentBuild:{primarySpec:h.spec,picks:[]}})),loadouts:Array.from({length:5},(_,i)=>({id:"party-"+(i+1),name:"Party "+(i+1),size:3,heroIds:[],ready:false})),questBoard:defaultQuestBoard(),quests:[],pendingEncounter:null,dungeonRuns:[]};}
function normalizeHeroRecord(heroRecord,fallback){const source=Object.assign({},fallback||{},heroRecord||{});return Object.assign({},source,{equipment:Object.assign(blankEquipment(),source.equipment||{}),talentBuild:Object.assign({primarySpec:source.spec,picks:[]},source.talentBuild||{})});}
function normalizeQuestRecord(record,heroes){const q=Object.assign({},record||{});const legacyDifficulty=q.tier;delete q.tier;const status=["available","active","completed"].includes(q.status)?q.status:"available";const ids=[...new Set(q.heroIds||[])].filter(id=>heroes.some(h=>h.id===id));const reward=Object.assign({gold:0,meta:"quest_marks",amount:0},q.reward||{});const difficulty=Number(q.difficulty??legacyDifficulty)||1;return Object.assign({},q,{id:String(q.id||""),title:String(q.title||("Quest Board Assignment · Difficulty "+difficulty)),difficulty,requiredHeroes:Number(q.requiredHeroes||q.partySize)||1,partySize:Number(q.partySize||q.requiredHeroes)||1,status,heroIds:ids,completedCount:Number(q.completedCount)||0,reward:{gold:Number(reward.gold)||0,meta:String(reward.meta||reward.meta_currency||"quest_marks"),amount:Number(reward.amount||reward.meta_amount)||0},round:Number(q.round)||0,sourceOfferId:q.sourceOfferId?String(q.sourceOfferId):null});}
function normalize(raw){const base=defaults(),saved=raw&&typeof raw==="object"?raw:{};base.faction=["alliance","horde"].includes(saved.faction)?saved.faction:"alliance";const savedHeroes=Array.isArray(saved.heroes)?saved.heroes:[];const byId=new Map(savedHeroes.map(h=>[h.id,h]));const seededIds=new Set(base.heroes.map(h=>h.id));base.heroes=base.heroes.map(h=>normalizeHeroRecord(byId.get(h.id),h));savedHeroes.filter(h=>h&&h.id&&!seededIds.has(h.id)).forEach(h=>base.heroes.push(normalizeHeroRecord(h)));const ls=Array.isArray(saved.loadouts)?saved.loadouts:[];base.loadouts=base.loadouts.map((l,i)=>{const s=ls[i]||{};const size=PARTY_SIZES.includes(Number(s.size))?Number(s.size):3;return {id:l.id,name:String(s.name||l.name).slice(0,40),size,heroIds:[...new Set((s.heroIds||[]).filter(id=>base.heroes.some(h=>h.id===id)))].slice(0,size),ready:Boolean(s.ready)};});const savedBoard=saved.questBoard&&typeof saved.questBoard==="object"?saved.questBoard:{};base.questBoard={round:Math.max(1,Number(savedBoard.round)||1),seed:String(savedBoard.seed||"questboard-v1"),offerIds:[...new Set((savedBoard.offerIds||[]).map(String))]};const savedQuests=Array.isArray(saved.quests)?saved.quests:[];base.quests=savedQuests.filter(q=>q&&q.id&&!(String(q.id).startsWith("quest-tier-")&&q.status==="available")).map(q=>normalizeQuestRecord(q,base.heroes));const encounter=saved.pendingEncounter&&typeof saved.pendingEncounter==="object"?saved.pendingEncounter:null;if(encounter){const heroIds=[...new Set(encounter.heroIds||[])].filter(id=>base.heroes.some(hero=>hero.id===id));base.pendingEncounter=Object.assign({},encounter,{heroIds,partySize:Number(encounter.partySize)||heroIds.length});}const dungeonRuns=Array.isArray(saved.dungeonRuns)?saved.dungeonRuns:[];base.dungeonRuns=dungeonRuns.filter(run=>run&&run.dungeonId).slice(-50).map(run=>({dungeonId:String(run.dungeonId),dungeonName:String(run.dungeonName||run.dungeonId),partySize:Number(run.partySize)||5,heroIds:[...new Set(run.heroIds||[])].filter(id=>base.heroes.some(hero=>hero.id===id)),loadoutId:run.loadoutId?String(run.loadoutId):null,faction:String(run.faction||base.faction),seed:Number(run.seed)||0,winnerTeam:Number(run.winnerTeam),victory:Boolean(run.victory),frame:Number(run.frame)||0,attempt:Number(run.attempt)||1}));return base;}
function load(){try{return normalize(JSON.parse(localStorage.getItem(STORAGE_KEY)||"null"));}catch(_){return defaults();}}
let state=load();
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(_){} if(!save.queued){save.queued=true;queueMicrotask(()=>{save.queued=false;global.dispatchEvent(new CustomEvent("warcraft:roster-changed",{detail:getState()}));});}}
function getState(){return state;}
function getQuestBoardState(){return state.questBoard;}
function getPendingEncounter(){return state.pendingEncounter;}
function getDungeonRuns(){return state.dungeonRuns;}
function getLatestDungeonRun(dungeonId){for(let index=state.dungeonRuns.length-1;index>=0;index-=1){if(state.dungeonRuns[index].dungeonId===dungeonId)return state.dungeonRuns[index];}return null;}
function setPendingEncounter(encounter){if(!encounter||typeof encounter!=="object")throw new Error("Encounter handoff is required.");const originalIds=(encounter.heroIds||[]).map(String);const heroIds=[...new Set(originalIds)];if(!heroIds.length)throw new Error("Encounter requires a party.");if(heroIds.some(id=>!hero(id)))throw new Error("Encounter party contains an unknown hero.");const partySize=Number(encounter.partySize)||heroIds.length;if(heroIds.length!==partySize||originalIds.length!==partySize)throw new Error("Encounter requires exactly "+partySize+" unique heroes.");if(encounter.kind==="dungeon"){const unavailable=heroIds.map(hero).filter(h=>!h||h.availability!=="available");if(unavailable.length)throw new Error("Every dungeon hero must be available.");if(encounter.loadoutId){const loadout=state.loadouts.find(entry=>entry.id===encounter.loadoutId);if(!loadout)throw new Error("Unknown saved party.");const check=validateLoadout(loadout,true);if(!check.valid)throw new Error(check.reason);if(loadout.size!==partySize||JSON.stringify(loadout.heroIds)!==JSON.stringify(heroIds))throw new Error("Saved party does not match encounter heroes.");}}state.pendingEncounter=Object.assign({},encounter,{heroIds,partySize,status:"pending",result:null});save();return state.pendingEncounter;}
function clearPendingEncounter(){if(state.pendingEncounter==null)return;state.pendingEncounter=null;save();}
function setQuestBoardOffers(offerIds){if(!Array.isArray(offerIds))throw new Error("Quest Board offers must be an array.");state.questBoard.offerIds=[...new Set(offerIds.map(String))];save();return state.questBoard;}
function advanceQuestRound(offerIds){if(!Array.isArray(offerIds))throw new Error("Quest Board offers must be an array.");state.questBoard.round+=1;state.questBoard.offerIds=[...new Set(offerIds.map(String))];save();return state.questBoard;}
function getFaction(){return state.faction;}
function setFaction(faction){const next=String(faction||"").toLowerCase();if(!["alliance","horde"].includes(next))throw new Error("Faction must be Alliance or Horde.");if(state.faction===next)return state.faction;state.faction=next;save();return state.faction;}
function validateRaceClass(raceLabel,classLabel,raceIndex){for(const faction of Object.values(raceIndex.factions||{})){const race=(faction.races||[]).find(r=>r.label===raceLabel);if(race)return race.available_classes.includes(classLabel);}return false;}
function hero(id){return state.heroes.find(h=>h.id===id)||null;}
function recruitHero(candidate,options){const next=Object.assign({},candidate||{});const required=["id","name","race","faction","classId","classLabel","spec","primary"];const missing=required.filter(key=>!next[key]);if(missing.length)throw new Error("Recruitment candidate missing: "+missing.join(", ")+".");if(hero(next.id))throw new Error(next.name+" is already on the roster.");const faction=String(next.faction).toLowerCase();if(faction!==state.faction)throw new Error("Candidate does not belong to the active faction.");const capacity=Number(options&&options.rosterCapacity);if(Number.isFinite(capacity)&&capacity>=0){const count=state.heroes.filter(h=>String(h.faction||"").toLowerCase()===faction).length;if(count>=capacity)throw new Error("Recruitment capacity reached.");}const recruited=normalizeHeroRecord(Object.assign({},next,{level:Number(next.level)||1,availability:"available",source:"recruitment"}));state.heroes.push(recruited);save();return recruited;}
function updateHero(id,patch,options){const h=hero(id);if(!h)return null;const next=Object.assign({},h,patch);if(options&&options.raceIndex&&!validateRaceClass(next.race,next.classLabel,options.raceIndex))throw new Error(next.race+" cannot be "+next.classLabel+".");Object.assign(h,patch);save();return h;}
function setEquipment(id,equipment){const h=hero(id);if(!h)return;const next=Object.assign(blankEquipment(),equipment||{});if(Object.keys(next).some(k=>!Object.prototype.hasOwnProperty.call(blankEquipment(),k)))throw new Error("Unknown equipment slot.");h.equipment=next;save();}
function setTalentBuild(id,build){const h=hero(id);if(!h)return;h.talentBuild=Object.assign({},h.talentBuild,build||{});if(build&&build.primarySpec)h.spec=build.primarySpec;save();}
function validateLoadout(loadout,checkAvailability){const ids=loadout.heroIds||[];const duplicate=new Set(ids).size!==ids.length;if(duplicate)return {valid:false,reason:"Duplicate heroes are not allowed."};if(ids.length!==loadout.size)return {valid:false,reason:"Requires exactly "+loadout.size+" heroes."};if(checkAvailability){const unavailable=ids.map(hero).filter(h=>!h||h.availability!=="available");if(unavailable.length)return {valid:false,reason:"Unavailable now: "+unavailable.map(h=>h?h.name:"Unknown hero").join(", ")};}return {valid:true,reason:"Ready"};}
function updateLoadout(index,patch){if(index<0||index>=5)return null;const current=state.loadouts[index];if(patch.size!=null&&!PARTY_SIZES.includes(Number(patch.size)))throw new Error("Party size must be 3, 5, 10, or 20.");const next=Object.assign({},current,patch);next.size=Number(next.size);next.heroIds=[...new Set(next.heroIds||[])].filter(id=>hero(id)).slice(0,next.size);if(next.ready&&!validateLoadout(next,false).valid)next.ready=false;state.loadouts[index]=next;save();return next;}
function dispatchQuest(offer,heroIds){if(!offer||typeof offer!=="object"||!offer.id)throw new Error("Quest dispatch requires a Quest Board offer.");const ids=[...new Set(heroIds||[])];const required=Number(offer.party_size||offer.requiredHeroes)||1;if(ids.length!==required)throw new Error((offer.title||"Quest")+" requires exactly "+required+" hero"+(required===1?"":"es")+".");const prior=state.quests.find(q=>q.round===state.questBoard.round&&q.sourceOfferId===offer.id);if(prior&&prior.status!=="available")throw new Error("This quest offer is already active or completed this round.");const selected=ids.map(hero);if(selected.some(h=>!h||h.availability!=="available"))throw new Error("Every dispatched hero must be available.");let quest=prior;if(prior){quest.status="active";quest.heroIds=ids;quest.lastResult=null;}else{quest=normalizeQuestRecord({id:"assignment-r"+state.questBoard.round+"-"+offer.id,sourceOfferId:offer.id,round:state.questBoard.round,title:offer.title,description:offer.description,difficulty:Number(offer.difficulty)||1,requiredHeroes:required,partySize:required,status:"active",heroIds:ids,completedCount:0,reward:{gold:Number(offer.reward&&offer.reward.gold)||0,meta:(offer.reward&&offer.reward.meta_currency)||"quest_marks",amount:Number(offer.reward&&offer.reward.meta_amount)||0}},state.heroes);state.quests.push(quest);}selected.forEach(h=>h.availability="on-quest");save();return quest;}
function completeQuest(identifier){const quest=state.quests.find(q=>q.id===String(identifier));if(!quest||quest.status!=="active")return null;quest.heroIds.map(hero).filter(Boolean).forEach(h=>h.availability="available");quest.status="completed";quest.completedCount=(quest.completedCount||0)+1;quest.lastResult="victory";quest.heroIds=[];save();return quest;}
function resolveQuestEncounter(identifier,victory){const quest=state.quests.find(q=>q.id===identifier);if(!quest||quest.status!=="active")return quest||null;quest.heroIds.map(hero).filter(Boolean).forEach(h=>h.availability="available");quest.lastResult=victory?"victory":"defeat";quest.attemptCount=(quest.attemptCount||0)+1;if(victory){quest.status="completed";quest.completedCount=(quest.completedCount||0)+1;}else{quest.status="available";}quest.heroIds=[];save();return quest;}
function resolvePendingEncounterResult(result){const encounter=state.pendingEncounter;if(!encounter)return null;if(encounter.status==="resolved"&&encounter.result)return encounter;const normalized={winnerTeam:Number(result&&result.winnerTeam),victory:Number(result&&result.winnerTeam)===0,frame:Number(result&&result.frame)||0};if(encounter.questAssignmentId)resolveQuestEncounter(encounter.questAssignmentId,normalized.victory);if(encounter.kind==="dungeon"&&encounter.dungeonId){const attempt=state.dungeonRuns.filter(run=>run.dungeonId===encounter.dungeonId).length+1;state.dungeonRuns.push({dungeonId:encounter.dungeonId,dungeonName:encounter.dungeonName||encounter.dungeonId,partySize:Number(encounter.partySize)||encounter.heroIds.length,heroIds:(encounter.heroIds||[]).slice(),loadoutId:encounter.loadoutId||null,faction:encounter.faction||state.faction,seed:Number(encounter.seed)||0,winnerTeam:normalized.winnerTeam,victory:normalized.victory,frame:normalized.frame,attempt});state.dungeonRuns=state.dungeonRuns.slice(-50);}state.pendingEncounter=Object.assign({},encounter,{status:"resolved",result:normalized});save();return state.pendingEncounter;}
function reset(){state=defaults();save();}
global.WarcraftRoster=Object.freeze({PARTY_SIZES,getState,getQuestBoardState,getPendingEncounter,getDungeonRuns,getLatestDungeonRun,setPendingEncounter,clearPendingEncounter,resolvePendingEncounterResult,setQuestBoardOffers,advanceQuestRound,getFaction,setFaction,hero,recruitHero,validateRaceClass,updateHero,setEquipment,setTalentBuild,validateLoadout,updateLoadout,dispatchQuest,completeQuest,resolveQuestEncounter,reset});
})(window);
