(function(global){
"use strict";
const STORAGE_KEY="warcraft.mockup.roster.v1";
const PARTY_SIZES=[3,5,10,20];
const DEFAULT_HEROES=[
{id:"mage",name:"Elowen",race:"Human",faction:"Alliance",classId:"mage",classLabel:"Mage",level:5,spec:"Fire",primary:"Intellect",availability:"available"},
{id:"rogue",name:"Valeera",race:"Undead",faction:"Horde",classId:"rogue",classLabel:"Rogue",level:4,spec:"Combat",primary:"Agility",availability:"available"},
{id:"warlock",name:"Mordren",race:"Undead",faction:"Horde",classId:"warlock",classLabel:"Warlock",level:3,spec:"Demonology",primary:"Intellect",availability:"on-quest"},
{id:"warrior",name:"Brom",race:"Dwarf",faction:"Alliance",classId:"warrior",classLabel:"Warrior",level:5,spec:"Arms",primary:"Strength",availability:"available"},
{id:"priest",name:"Sister Anwen",race:"Human",faction:"Alliance",classId:"priest",classLabel:"Priest",level:2,spec:"Holy",primary:"Intellect",availability:"available"},
{id:"druid",name:"Thorn",race:"Night Elf",faction:"Alliance",classId:"druid",classLabel:"Druid",level:4,spec:"Feral",primary:"Agility",availability:"available"},
{id:"hunter",name:"Rifleman Keg",race:"Dwarf",faction:"Alliance",classId:"hunter",classLabel:"Hunter",level:3,spec:"Marksmanship",primary:"Agility",availability:"available"},
{id:"paladin",name:"Arthoran",race:"Human",faction:"Alliance",classId:"paladin",classLabel:"Paladin",level:5,spec:"Retribution",primary:"Strength",availability:"on-quest"},
{id:"shaman",name:"Gorak",race:"Tauren",faction:"Horde",classId:"shaman",classLabel:"Shaman",level:1,spec:"Enhancement",primary:"Agility",availability:"available"}
];
function blankEquipment(){return {Head:null,Chest:null,Pants:null,Feet:null,Gloves:null,Weapon:null,Trinket:null};}
function defaultQuests(){return [1,2,3,4,5].map((tier,i)=>({id:"quest-tier-"+tier,tier,requiredHeroes:[1,3,5,10,20][i],status:"available",heroIds:[],completedCount:0,reward:{gold:tier*250,meta:"quest_marks",amount:tier}}));}
function defaults(){return {heroes:DEFAULT_HEROES.map(h=>Object.assign({},h,{equipment:blankEquipment(),talentBuild:{primarySpec:h.spec,picks:[]}})),loadouts:Array.from({length:5},(_,i)=>({id:"party-"+(i+1),name:"Party "+(i+1),size:3,heroIds:[],ready:false})),quests:defaultQuests()};}
function normalize(raw){const base=defaults(),saved=raw&&typeof raw==="object"?raw:{};const byId=new Map((saved.heroes||[]).map(h=>[h.id,h]));base.heroes=base.heroes.map(h=>{const s=byId.get(h.id)||{};return Object.assign({},h,s,{equipment:Object.assign(blankEquipment(),s.equipment||{}),talentBuild:Object.assign({},h.talentBuild,s.talentBuild||{})});});const ls=Array.isArray(saved.loadouts)?saved.loadouts:[];base.loadouts=base.loadouts.map((l,i)=>{const s=ls[i]||{};const size=PARTY_SIZES.includes(Number(s.size))?Number(s.size):3;return {id:l.id,name:String(s.name||l.name).slice(0,40),size,heroIds:[...new Set((s.heroIds||[]).filter(id=>base.heroes.some(h=>h.id===id)))].slice(0,size),ready:Boolean(s.ready)};});const qs=Array.isArray(saved.quests)?saved.quests:[];base.quests=base.quests.map((q,i)=>Object.assign({},q,qs[i]||{},{tier:q.tier,requiredHeroes:q.requiredHeroes,heroIds:[...new Set(((qs[i]||{}).heroIds||[]).filter(id=>base.heroes.some(h=>h.id===id)))]}));return base;}
function load(){try{return normalize(JSON.parse(localStorage.getItem(STORAGE_KEY)||"null"));}catch(_){return defaults();}}
let state=load();
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(_){} if(!save.queued){save.queued=true;queueMicrotask(()=>{save.queued=false;global.dispatchEvent(new CustomEvent("warcraft:roster-changed",{detail:getState()}));});}}
function getState(){return state;}\nfunction validateRaceClass(raceLabel,classLabel,raceIndex){for(const faction of Object.values(raceIndex.factions||{})){const race=(faction.races||[]).find(r=>r.label===raceLabel);if(race)return race.available_classes.includes(classLabel);}return false;}
function hero(id){return state.heroes.find(h=>h.id===id)||null;}
function updateHero(id,patch,options){const h=hero(id);if(!h)return null;const next=Object.assign({},h,patch);if(options&&options.raceIndex&&!validateRaceClass(next.race,next.classLabel,options.raceIndex))throw new Error(next.race+" cannot be "+next.classLabel+".");Object.assign(h,patch);save();return h;}
function setEquipment(id,equipment){const h=hero(id);if(!h)return;const next=Object.assign(blankEquipment(),equipment||{});if(Object.keys(next).some(k=>!Object.prototype.hasOwnProperty.call(blankEquipment(),k)))throw new Error("Unknown equipment slot.");h.equipment=next;save();}
function setTalentBuild(id,build){const h=hero(id);if(!h)return;h.talentBuild=Object.assign({},h.talentBuild,build||{});if(build&&build.primarySpec)h.spec=build.primarySpec;save();}
function validateLoadout(loadout,checkAvailability){const ids=loadout.heroIds||[];const duplicate=new Set(ids).size!==ids.length;if(duplicate)return {valid:false,reason:"Duplicate heroes are not allowed."};if(ids.length!==loadout.size)return {valid:false,reason:"Requires exactly "+loadout.size+" heroes."};if(checkAvailability){const unavailable=ids.map(hero).filter(h=>!h||h.availability!=="available");if(unavailable.length)return {valid:false,reason:"Unavailable now: "+unavailable.map(h=>h?h.name:"Unknown hero").join(", ")};}return {valid:true,reason:"Ready"};}
function updateLoadout(index,patch){if(index<0||index>=5)return null;const current=state.loadouts[index];if(patch.size!=null&&!PARTY_SIZES.includes(Number(patch.size)))throw new Error("Party size must be 3, 5, 10, or 20.");const next=Object.assign({},current,patch);next.size=Number(next.size);next.heroIds=[...new Set(next.heroIds||[])].filter(id=>hero(id)).slice(0,next.size);if(next.ready&&!validateLoadout(next,false).valid)next.ready=false;state.loadouts[index]=next;save();return next;}
function dispatchQuest(tier,heroIds){const quest=state.quests.find(q=>q.tier===tier);if(!quest)throw new Error("Unknown quest tier.");const ids=[...new Set(heroIds||[])];if(ids.length!==quest.requiredHeroes)throw new Error("Tier "+tier+" requires exactly "+quest.requiredHeroes+" hero"+(quest.requiredHeroes===1?"":"es")+".");const selected=ids.map(hero);if(selected.some(h=>!h||h.availability!=="available"))throw new Error("Every dispatched hero must be available.");quest.heroIds=ids;quest.status="active";selected.forEach(h=>h.availability="on-quest");save();return quest;}
function completeQuest(tier){const quest=state.quests.find(q=>q.tier===tier);if(!quest||quest.status!=="active")return null;quest.heroIds.map(hero).filter(Boolean).forEach(h=>h.availability="available");quest.status="completed";quest.completedCount=(quest.completedCount||0)+1;quest.heroIds=[];save();return quest;}
function reset(){state=defaults();save();}
global.WarcraftRoster=Object.freeze({PARTY_SIZES,getState,hero,validateRaceClass,updateHero,setEquipment,setTalentBuild,validateLoadout,updateLoadout,dispatchQuest,completeQuest,reset});
})(window);
