const Campaign=window.WarcraftCampaign,Roster=window.WarcraftRoster,Progression=window.WarcraftContentProgression,Assignments=window.WarcraftContentAssignments;
const $=id=>document.getElementById(id);let catalog=null,dungeons=null,selectedIds=[];
function focusFor(level){return level<=1?"Quest":level===2?"Incursion":"Dungeon";}
function availableHeroes(){return Roster.getState().heroes.filter(h=>h.availability==="available");}
function questOptions(){return Roster.getState().quests.filter(q=>q.status==="available").map(q=>({kind:"quest",id:q.id,label:q.title||q.id,partySize:Number(q.requiredHeroes)||1,record:q}));}
function incursionOptions(){return [{kind:"incursion",id:"frontier-incursion",label:"Frontier Incursion",partySize:5}];}
function dungeonOptions(){return dungeons.dungeons.map(d=>({kind:"dungeon",id:d.id,label:d.display_name,partySize:5,record:d}));}
function options(){const level=Campaign.getBaseLevel();return Progression.available(level).flatMap(s=>s.id==="quest"?questOptions():s.id==="incursion"?incursionOptions():s.id==="dungeon"?dungeonOptions():[]);}
function current(){return options().find(o=>o.kind+":"+o.id===$("embarkContent").value)||options()[0];}
function render(){const level=Campaign.getBaseLevel(),faction=Campaign.getActiveFaction(),opts=options(),select=$("embarkContent");$("embarkFocus").textContent="Base Level "+level+" focus · "+focusFor(level);$("embarkFaction").textContent=faction==="horde"?"Horde":"Alliance";select.innerHTML=opts.map(o=>'<option value="'+o.kind+":"+o.id+'">'+o.label+" · "+o.kind+"</option>").join("");selectedIds=[];renderSelection();}
function renderSelection(){const item=current(),root=$("embarkRoster");if(!item){$("embarkDetail").textContent="No manual content is currently available.";root.innerHTML="";return;}$("embarkDetail").innerHTML="<strong>"+item.label+"</strong><span>"+item.kind.toUpperCase()+" · "+item.partySize+" hero"+(item.partySize===1?"":"es")+"</span>";root.innerHTML="";if(item.kind==="dungeon"){const parties=Roster.getLoadouts().filter(p=>Roster.validateLoadout(p,true).valid);parties.forEach(p=>{const b=document.createElement("button");b.type="button";b.className="embark-hero";b.textContent=p.name+" · ready 5";b.onclick=()=>{selectedIds=Roster.partyHeroIds(p);root.querySelectorAll(".is-selected").forEach(x=>x.classList.remove("is-selected"));b.classList.add("is-selected");b.dataset.loadoutId=p.id;};root.appendChild(b);});return;}availableHeroes().forEach(h=>{const b=document.createElement("button");b.type="button";b.className="embark-hero";b.textContent=h.name+" · "+h.classLabel;b.onclick=()=>{if(selectedIds.includes(h.id))selectedIds=selectedIds.filter(id=>id!==h.id);else if(selectedIds.length<item.partySize)selectedIds.push(h.id);b.classList.toggle("is-selected",selectedIds.includes(h.id));};root.appendChild(b);});}
function formationFor(item){if(item.kind!=="dungeon")return null;const loadout=Roster.getLoadouts().find(p=>JSON.stringify(Roster.partyHeroIds(p))===JSON.stringify(selectedIds));return loadout?{type:"party",faction:Campaign.getActiveFaction(),slots:loadout.slots.map(s=>({id:s.id,heroId:s.heroId}))}:null;}
function confirm(){const item=current();if(!item)return;try{if(selectedIds.length!==item.partySize)throw new Error("Select exactly "+item.partySize+" heroes.");Campaign.validateHeroIds(selectedIds);const unavailable=selectedIds.map(Roster.hero).filter(h=>!h||h.availability!=="available");if(unavailable.length)throw new Error("Every selected hero must be available.");const seed=(Campaign.getClock().day*1000+Campaign.getClock().phaseAdvances*17+item.id.length)>>>0;const encounter={kind:item.kind,faction:Campaign.getActiveFaction(),heroIds:selectedIds.slice(),partySize:item.partySize,seed,source:"embark",returnTo:"embark.html",encounterName:item.label};if(item.kind==="quest")encounter.questAssignmentId=item.id;if(item.kind==="dungeon"){encounter.dungeonId=item.id;encounter.dungeonName=item.label;encounter.npcPoolId=item.record.npc_pool_id;encounter.formation=formationFor(item);const loadout=Roster.getLoadouts().find(p=>JSON.stringify(Roster.partyHeroIds(p))===JSON.stringify(selectedIds));encounter.loadoutId=loadout&&loadout.id;}Roster.setPendingEncounter(encounter);Campaign.confirmEmbark(encounter);location.href="./battle.html?encounter="+encodeURIComponent(item.kind)+(item.kind==="dungeon"?"&dungeon="+encodeURIComponent(item.id):item.kind==="quest"?"&quest="+encodeURIComponent(item.id):"");}catch(e){$("embarkError").textContent=e.message;}}
async function init(){[catalog,dungeons]=await Promise.all([fetch("../data/content/progression.json").then(r=>r.json()),fetch("../data/dungeons/catalog.json").then(r=>r.json())]);Progression.configure(catalog);Assignments.configure(catalog);render();$("embarkContent").addEventListener("change",()=>{selectedIds=[];renderSelection();});$("confirmEmbark").addEventListener("click",confirm);window.addEventListener("warcraft:campaign-changed",e=>{if(e.detail?.reason==="faction")render();});}init();